# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  api:
    image: businesscardsapi
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Database__ConnectionString: mongodb://mongo:27017
      Database__DatabaseName: BusinessCards
      Database__CardsCollectionName: Cards
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
